//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Map.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Map.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string _ReleaseCount {
            get {
                return ResourceManager.GetString("_ReleaseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.0.2.
        /// </summary>
        public static string _Version {
            get {
                return ResourceManager.GetString("_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Activities.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a run....
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new run.
        /// </summary>
        public static string AddNewRun {
            get {
                return ResourceManager.GetString("AddNewRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app needs your permission to access to your location data and works correctly. Your location data will be completely safe! Do you want to enable access to location data ? You could change this setting later by go to &quot;Settings -&gt; Enable location access&quot;.
        /// </summary>
        public static string AllowLocationMsg {
            get {
                return ResourceManager.GetString("AllowLocationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just run.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto heading.
        /// </summary>
        public static string AutoHeading {
            get {
                return ResourceManager.GetString("AutoHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play music automatically when I start the run.
        /// </summary>
        public static string AutoStartMusic {
            get {
                return ResourceManager.GetString("AutoStartMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Pace: .
        /// </summary>
        public static string AvgPace {
            get {
                return ResourceManager.GetString("AvgPace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Speed: .
        /// </summary>
        public static string AvgSpeed {
            get {
                return ResourceManager.GetString("AvgSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories: .
        /// </summary>
        public static string BurnedCalories {
            get {
                return ResourceManager.GetString("BurnedCalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to restart the application to take whole effect for changing language!.
        /// </summary>
        public static string ChangingLanguageWarning {
            get {
                return ResourceManager.GetString("ChangingLanguageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Pitch Level.
        /// </summary>
        public static string DefaultPitchLevel {
            get {
                return ResourceManager.GetString("DefaultPitchLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Zoom Level.
        /// </summary>
        public static string DefaultZoomLevel {
            get {
                return ResourceManager.GetString("DefaultZoomLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data will be erased and can&apos;t be restored. Are you sure about deleting this account?.
        /// </summary>
        public static string DelAccMsg {
            get {
                return ResourceManager.GetString("DelAccMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete these data?.
        /// </summary>
        public static string DeleteConfirmMsg {
            get {
                return ResourceManager.GetString("DeleteConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance: .
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration: .
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail (For signing up only).
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is empty!.
        /// </summary>
        public static string EmptyData {
            get {
                return ResourceManager.GetString("EmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable location data access.
        /// </summary>
        public static string EnableLocationAccess {
            get {
                return ResourceManager.GetString("EnableLocationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit?.
        /// </summary>
        public static string ExitConfirmMessage {
            get {
                return ResourceManager.GetString("ExitConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t complete this action. Please check your network connection and try again later!.
        /// </summary>
        public static string FailedAction {
            get {
                return ResourceManager.GetString("FailedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding your location, please wait....
        /// </summary>
        public static string FindingLocation {
            get {
                return ResourceManager.GetString("FindingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this your first time to run this application?
        ///Give it some of your infomation to get the most accurate results!.
        /// </summary>
        public static string FirstRegMsg {
            get {
                return ResourceManager.GetString("FirstRegMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure that you have turned on GPS location service !.
        /// </summary>
        public static string GPSErrorMessage {
            get {
                return ResourceManager.GetString("GPSErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Grade is expressed in percent (amount of vertical change in some horizontal distance, that ratio being multiplied by 100 to become a percent). For example: grade of 2% means with every 1 meter in long, it gains 0.02 (2%) meters in height.
        ///It&apos;s 2% by default..
        /// </summary>
        public static string GradeExplain {
            get {
                return ResourceManager.GetString("GradeExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, {0}!.
        /// </summary>
        public static string HelloUser {
            get {
                return ResourceManager.GetString("HelloUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your provided user information again!.
        /// </summary>
        public static string InvalidUserInfo {
            get {
                return ResourceManager.GetString("InvalidUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Music player.
        /// </summary>
        public static string MusicPlayer {
            get {
                return ResourceManager.GetString("MusicPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my location.
        /// </summary>
        public static string MyLocation {
            get {
                return ResourceManager.GetString("MyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Ver 1.2.0.2
        ///- Minor bugs fixed.
        ///
        ///* Ver 1.2.0.1
        ///- Fixed requires data connection on start up bug.
        ///- Fixed wrong order of runs bug.
        ///
        ///* Ver 1.2.0.0
        ///- Added music player.
        ///- Automatically check for update.
        ///- Minor bugs fixed.
        ///- Improved UI.
        ///
        ///* Ver 1.1.0.2
        ///- Added training process statistics charts (testing).
        ///- Diagnosis of obesity.
        ///- Fixed small bugs
        ///- Improved UI &amp; performance.
        ///
        ///* Ver 1.0.0.2
        ///- Normal operation even when the lock screen is active.
        ///- Supported both Vietnamese and English.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewReleaseMsg {
            get {
                return ResourceManager.GetString("NewReleaseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update is available.
        /// </summary>
        public static string NewUpdateAvailable {
            get {
                return ResourceManager.GetString("NewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of this application is now available. Do you want to update it right away ?.
        /// </summary>
        public static string NewUpdateAvailableMsg {
            get {
                return ResourceManager.GetString("NewUpdateAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no run in that time..
        /// </summary>
        public static string NoDataMsg {
            get {
                return ResourceManager.GetString("NoDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s none of your locations found in this run. Maybe it&apos;s because you have accidentally hit the &apos;Finished&apos; button way too soon. Feel free to delete this run :).
        /// </summary>
        public static string NoGeoFoundMsg {
            get {
                return ResourceManager.GetString("NoGeoFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No songs in library..
        /// </summary>
        public static string NoSongMsg {
            get {
                return ResourceManager.GetString("NoSongMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity.
        /// </summary>
        public static string Obesity {
            get {
                return ResourceManager.GetString("Obesity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over weight.
        /// </summary>
        public static string OverWeight {
            get {
                return ResourceManager.GetString("OverWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match!.
        /// </summary>
        public static string PasswordsNotMatch {
            get {
                return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your privacy is important to us. 
        ///This application uses your location to record your running progress. It will be stored in your phone&apos;s memory and you could delete it at anytime. Your location won&apos;t be displayed to anyone until and unless you allow. For any changes in privacy policy, we will let you know immediately.
        ///If you have questions about privacy policy, contact us via lehainam.it@outlook.com or tap the addresses provided below..
        /// </summary>
        public static string PrivacyPolicyContent {
            get {
                return ResourceManager.GetString("PrivacyPolicyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like you found this app interesting. Please vote for us :).
        /// </summary>
        public static string RateMsg {
            get {
                return ResourceManager.GetString("RateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in again.
        /// </summary>
        public static string ReLoginMsg {
            get {
                return ResourceManager.GetString("ReLoginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type (For signing up only).
        /// </summary>
        public static string ReTypePassword {
            get {
                return ResourceManager.GetString("ReTypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running....
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Route.
        /// </summary>
        public static string RunRoute {
            get {
                return ResourceManager.GetString("RunRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this activity?.
        /// </summary>
        public static string SaveConfirmMessage {
            get {
                return ResourceManager.GetString("SaveConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved!.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey! Let&apos;s go jogging with this app
        ///http://www.windowsphone.com/en-us/store/app/just-run/32718529-30bd-482c-b6e3-e876aba10a15.
        /// </summary>
        public static string ShareMsg {
            get {
                return ResourceManager.GetString("ShareMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you tried Just Run ?.
        /// </summary>
        public static string ShareSubject {
            get {
                return ResourceManager.GetString("ShareSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this app via E-mail.
        /// </summary>
        public static string ShareThisAppEmail {
            get {
                return ResourceManager.GetString("ShareThisAppEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this app via SMS.
        /// </summary>
        public static string ShareThisAppSMS {
            get {
                return ResourceManager.GetString("ShareThisAppSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re currently signed in with username:.
        /// </summary>
        public static string SignedInWith {
            get {
                return ResourceManager.GetString("SignedInWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string SongDuration {
            get {
                return ResourceManager.GetString("SongDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song title.
        /// </summary>
        public static string SongTitle {
            get {
                return ResourceManager.GetString("SongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed: .
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated your data!.
        /// </summary>
        public static string SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing account.
        /// </summary>
        public static string SyncingAcc {
            get {
                return ResourceManager.GetString("SyncingAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing your data....
        /// </summary>
        public static string SyncingData {
            get {
                return ResourceManager.GetString("SyncingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync now.
        /// </summary>
        public static string SyncNow {
            get {
                return ResourceManager.GetString("SyncNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto back up &amp; sync my data.
        /// </summary>
        public static string SyncOnlineLabel {
            get {
                return ResourceManager.GetString("SyncOnlineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Objects.
        /// </summary>
        public static string ThreeDObjects {
            get {
                return ResourceManager.GetString("ThreeDObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: .
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total calories: .
        /// </summary>
        public static string TotalCalories {
            get {
                return ResourceManager.GetString("TotalCalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total distance: .
        /// </summary>
        public static string TotalDistance {
            get {
                return ResourceManager.GetString("TotalDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total duration: .
        /// </summary>
        public static string TotalDuration {
            get {
                return ResourceManager.GetString("TotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on auto sync data?.
        /// </summary>
        public static string TurnOnSyncingMsg {
            get {
                return ResourceManager.GetString("TurnOnSyncingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under weight.
        /// </summary>
        public static string UnderWeight {
            get {
                return ResourceManager.GetString("UnderWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Information.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: .
        /// </summary>
        public static string UsernameTxt {
            get {
                return ResourceManager.GetString("UsernameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new ?.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account.
        /// </summary>
        public static string YourAccount {
            get {
                return ResourceManager.GetString("YourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your last run: .
        /// </summary>
        public static string YourLastRun {
            get {
                return ResourceManager.GetString("YourLastRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Progress.
        /// </summary>
        public static string YourProgress {
            get {
                return ResourceManager.GetString("YourProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your runs.
        /// </summary>
        public static string YourRuns {
            get {
                return ResourceManager.GetString("YourRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your stats.
        /// </summary>
        public static string YourStats {
            get {
                return ResourceManager.GetString("YourStats", resourceCulture);
            }
        }
    }
}
